Repository numaproj/numalogic-prometheus, pull requests merged in 2023-04, with the labels that each got.

#115 fix: catch braoder redis exceptions
  numaprom/clients/__init__.py
  numaprom/clients/prometheus.py
  numaprom/clients/redis.py
  numaprom/tools.py
  numaprom/udf/postprocess.py
  numaprom/udf/window.py
  numaprom/udsink/train.py
  numaprom/udsink/train_rollout.py
  pyproject.toml
  tests/__init__.py
  tests/test_prometheus.py
  tests/test_trainer.py
Labels: bug

#117 chore: update poetry version to 1.4.2 in dockerfile
  Dockerfile
  poetry.lock
Labels: chore

#124 fix: manifests for open source
  docs/metrics.md
  manifests/argoworkflows/kustomization.yaml
  manifests/argoworkflows/numalogic-training-workflow-template.yaml
  manifests/argoworkflows/workflow-role.yaml
  manifests/argoworkflows/workflow-rolebinding.yaml
  manifests/pipeline/numalogic-prometheus-app-configs.yaml
  manifests/pipeline/numalogic-prometheus-config.yaml
  manifests/pipeline/numalogic-prometheus-default-configs.yaml
  manifests/pipeline/numalogic-prometheus-pipeline.yaml
  manifests/prerequisites/argoworkflows/kustomization.yaml
  manifests/prerequisites/argoworkflows/namespace.yaml
  manifests/prerequisites/numaflow/kustomization.yaml
Labels: documentation

#126 fix: catch inference errors and send for static thresholding
  Makefile
  numaprom/entities.py
  numaprom/udf/inference.py
  numaprom/udf/threshold.py
  pyproject.toml
  tests/udf/test_inference.py
Labels: bug
