Repository numaproj/numalogic-prometheus, pull requests merged in 2023-06, with the labels that each got.

#141 feat: Add caching support
  README.md
  numaprom/_config.py
  numaprom/udf/inference.py
  numaprom/udf/preprocess.py
  numaprom/udf/threshold.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#143 feat: add loguru for logging
  numaprom/__init__.py
  numaprom/_config.py
  numaprom/clients/prometheus.py
  numaprom/clients/redis.py
  numaprom/clients/sentinel.py
  numaprom/entities.py
  numaprom/tools.py
  numaprom/udf/filter.py
  numaprom/udf/inference.py
  numaprom/udf/postprocess.py
  numaprom/udf/preprocess.py
  numaprom/udf/threshold.py
  numaprom/udf/window.py
  numaprom/udsink/train.py
  numaprom/udsink/train_rollout.py
  numaprom/watcher.py
  poetry.lock
  pyproject.toml
Labels: chore

#148 fix: create new copy of array while retrieving from payload
  .dockerignore
  .flake8
  .github/workflows/lint.yml
  .pre-commit-config.yaml
  Makefile
  numaprom/clients/prometheus.py
  numaprom/clients/redis.py
  numaprom/clients/sentinel.py
  numaprom/entities.py
  numaprom/factory.py
  numaprom/udf/filter.py
  numaprom/udf/inference.py
  numaprom/udf/postprocess.py
  numaprom/udf/preprocess.py
  numaprom/udf/threshold.py
  numaprom/udf/window.py
  numaprom/udsink/train_rollout.py
  numaprom/watcher.py
  poetry.lock
  pyproject.toml
  tests/test_trainer.py
  tests/tools.py
  tests/udf/test_filter.py
  tests/udf/test_inference.py
  tests/udf/test_postprocess.py
  tests/udf/test_preprocess.py
  tests/udf/test_threshold.py
  tests/udf/test_window.py
Labels: bug, chore
